appName: "nginx"
environment: dev

image:
  repository: "nginx"
  tag: "latest"

configmap:
  DEBUG: 'true'

secrets:
  SERVER_ADD: "/server/addr"

volume:
  enabled: true
  resources:
    requests:
      storage: 2Gi
  storageClass:
    name: sc
    create:
      provisioner: "aws-ebs-csi-driver"
      parameters:
        type: gp3
        iops: "3000"