apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: agent-demo
    app.kubernetes.io/name: agent-demo
    app.kubernetes.io/version: 1.16.0
  name: agent-demo
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: agent-demo
      app.kubernetes.io/name: agent-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: agent-demo
        app.kubernetes.io/name: agent-demo
    spec:
      serviceAccountName: agent-demo
      containers:
        - args:
            - '--config=/etc/otelcol-contrib/otel-collector-config_test.yaml'
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: 'otel/opentelemetry-collector-contrib:0.68.0'
          imagePullPolicy: IfNotPresent
          name: agent
          ports:
            - containerPort: 4317
              name: otelgrpc
              protocol: TCP
            - containerPort: 4318
              name: otelhttp
              protocol: TCP
            - containerPort: 9000
              name: metrics
              protocol: TCP
          volumeMounts:
            - mountPath: /var/log
              name: varlog
              readOnly: true
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
            - mountPath: /etc/otelcol-contrib/
              name: data
              readOnly: true
      volumes:
        - hostPath:
            path: /var/log
            type: ''
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
            type: ''
          name: varlibdockercontainers
        - configMap:
            defaultMode: 420
            name: demo
          name: data
