{{- if .Values.rbac.create  -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "agent.labels" . | nindent 4 }}
  name: {{ include "agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "agent.serviceAccountName" . }}
{{ include "agent.namespace" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "agent.fullname" . }}
{{- end }}
