apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
data:
  config.yaml: |
    receivers:
      prometheus:
        config:
          scrape_configs:
{{- if and .Values.receivers.prometheus.default.enabled ( not (empty .Values.receivers.prometheus.default.scrape_configs)) }}
{{- tpl (toYaml .Values.receivers.prometheus.default.scrape_configs) . | nindent 12 }}
{{- end}}
{{- if .Values.receivers.prometheus.kubernetes.enabled}}
{{- tpl (toYaml .Values.receivers.prometheus.kubernetes.scrape_configs) . | nindent 12 }}
{{- end}}
{{- if .Values.receivers.prometheus.append.enabled}}
{{- tpl (toYaml .Values.receivers.prometheus.append.scrape_configs) . | nindent 12 }}
{{- end}}
{{- tpl (toYaml .Values.config.receivers) . | nindent 6 }}

    exporters:
{{- tpl (toYaml .Values.config.exporters) . | nindent 6 }}

    processors:
{{- tpl (toYaml .Values.config.processors) . | nindent 6 }}

    extensions:
{{- tpl (toYaml .Values.config.extensions) . | nindent 6 }}

    service:
{{- tpl (toYaml .Values.config.service) . | nindent 6 }}