apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $port := .Values.service.ports }}
    - port: {{ $port.port }}
      targetPort: {{ $port.name }}
      protocol: TCP
      name: {{ $port.name }}
    {{- end }}
  selector:
    {{- include "agent.selectorLabels" . | nindent 4 }}
