apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: otel
      protocol: TCP
      name: otel
    - port: 4318
      targetPort: http
      protocol: TCP
      name: http
    - port: 24224
      targetPort: fluentforward
      protocol: TCP
      name: fluentforward
  selector:
    {{- include "agent.selectorLabels" . | nindent 4 }}
