{{- if .Values.configmap -}}
{{- $appname := printf "%s" (include "name" .) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $appname }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $appname }}
    appver: "{{ .Values.image.tag }}"
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: "{{ .Release.Name }}"
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-5"
data:
{{- range $key, $value := .Values.configmap }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end -}}