{{- if and .Values.ingress.tls .Values.vaultCert -}}
{{- $fqdn := printf "%s" (include "fqdn" . | replace "." "-") -}}
{{- $vaultPath := printf "certs/%s" (include "vaultCert" .) -}}
apiVersion: "koudingspawn.de/v1"
kind: Vault
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ $fqdn }}
  labels:
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-4"  
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  path: {{ $vaultPath }}
  type: "CERT"
{{- end -}}