{{- if .Values.rbac.create -}}
{{- $appname := printf "%s" (include "name" .) -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Namespace }}-{{ $appname }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-{{ $appname }}
rules:
- apiGroups:
  - ""
  resources:
{{ toYaml .Values.rbac.resources | indent 2 }}
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-{{ $appname }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Namespace }}-{{ $appname }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Namespace }}-{{ $appname }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}