{{- if .Values.serviceExternalName.enabled -}}
  {{- $root := . -}}
  {{- $appname := printf "%s" (include "name" .) -}}
  {{- range $key, $value := .Values.serviceExternalName.services }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $root.Release.Namespace }}
  name: {{ $key }}
  labels:
    app: {{ $appname }}
    chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version }}"
    release: "{{ $root.Release.Name }}"
spec:
  externalName: {{ $value.externalName }}
  sessionAffinity: None
  type: ExternalName
  {{- end -}}
{{- end -}}